name: dev_assignment_2
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  google_fonts: ^6.1.0
  intl: ^0.18.0
  sqflite: ^2.3.0
  table_calendar:
    git:
      url: https://github.com/hrithikm2/table_calendar.git
      ref: master
  uuid: ^4.3.3
dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/.
